### ISSUE TITLE
Should i build QT from source?

### ISSUE THREAD

**Issue by moonspirit** [sfederic/VEngine#2]
like using qt 5.15.0 source code [qt-everywhere-src-5.15.0.tar.xz](https://download.qt.io/official_releases/qt/5.15/5.15.0/single/qt-everywhere-src-5.15.0.tar.xz)?

**Comment by moonspirit** [comment]
Besides, when i install directxtk with donet, it failes with error:

>dotnet add package directxtk_desktop_win10 --version 2021.8.2.1
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'add' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

I have installed visual studio 2022 and using its dotnet.exe, seems not seen an valid .NET SDK? which version should i use?

**Comment by moonspirit** [comment]
add directxtk to VEngine failed: 

VEngine>dotnet add package directxtk_desktop_win10 --version 2021.8.2.1
C:\Engine\Engine\VEngine\VEngine.vcxproj(20,3): error MSB4019: 找不到导入的项目“C:\Microsoft.Cpp.Default.props”。请确 认 Import 声明“\
Microsoft.Cpp.Default.props”中的表达式正确，且文件位于磁盘上。
无法为项目“C:\Engine\Engine\VEngine\VEngine.vcxproj”创建依赖关系图文件。无法添加包引用。

**Comment by sfederic** [comment]
> like using qt 5.15.0 source code [qt-everywhere-src-5.15.0.tar.xz](https://download.qt.io/official_releases/qt/5.15/5.15.0/single/qt-everywhere-src-5.15.0.tar.xz)?

Qt has a binary installer https://www.qt.io/download-qt-installer?hsCtaTracking=99d9dd4f-5681-48d2-b096-470725510d34%7C074ddad0-fdef-4e53-8aa8-5e8a876d6ab4 that is a bit easier. You'd have to then add Qt's include path to Visual Studio.

> Besides, when i install directxtk with donet, it failes with error:

Try using the nuget package manager in Visual Studio for a C++ project.

_Note: Please don't actually use the engine. It's junk_.
